apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzczEzMzc=  
  MYSQL_DATABASE: ZGJfMTMzNw==  
  MYSQL_USER: eWlzbWFpbGk=  
  MYSQL_PASSWORD: cGFzczEzMzc= 

#  commands to encode the values
    # echo -n 'pass1337' | base64
    # echo -n 'db_1337' | base64
    # echo -n 'yismaili' | base64
    # echo -n 'pass1337' | base64
