apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  NGINX_SERVER_NAME: "yismaili42.fr"
  NGINX_SSL_CERT: |-
    -----BEGIN CERTIFICATE-----
    /etc/ssl/certs/nginx.crt
    -----END CERTIFICATE-----
  NGINX_SSL_KEY: |-
    -----BEGIN PRIVATE KEY-----
    /etc/ssl/private/nginx.key
    -----END PRIVATE KEY-----

