apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # This selector should match the labels of your Deployment or Pods
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080 # This should match the containerPort of your Pods

# each configuration file has 3 parts

# 1 ) metadata
# 2 ) specification
# 3 ) status 