apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels: # Corrected typo: "matchLasbels" to "matchLabels"
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: # Corrected the indentation of "spec" for the pod template
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80 # Corrected the indentation of "containerPort"
