apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-rwx-rep2
provisioner: pxd.portworx.com
parameters:
  repl: "2"
  sharedv4: "true"
  sharedv4_svc_type: "ClusterIP"
reclaimPolicy: Retain
allowVolumeExpansion: true