apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: localhost:5000/wp:v1
        # volumeMounts:
        # - name: wordpress-data
        #   mountPath: /Users/yismaili/Desktop/k8s/Inception/volume
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: wordpress-configmap
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: px-sharedv4-pvc