kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: px-sharedv4-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-rwx-rep2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi