apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: px-sharedv4-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # Set the desired storage capacity
  storageClassName: portworx-rwx-rep2  # Reference the StorageClass name
